"""create remaining tables

Revision ID: 1985e30127ab
Revises: 98c19491f932
Create Date: 2026-07-27 18:29:39.747710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1985e30127ab'
down_revision: Union[str, Sequence[str], None] = '98c19491f932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_name', name='uq_user_group')
    )
    op.create_index(op.f('ix_user_group_memberships_group_name'), 'user_group_memberships', ['group_name'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_id'), 'user_group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_user_id'), 'user_group_memberships', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('targeting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=False)
    op.add_column('flags', sa.Column('type', sa.String(), nullable=False))
    op.add_column('flags', sa.Column('default_value', sa.String(), nullable=True))
    op.add_column('flags', sa.Column('owner_team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'owner_team')
    op.drop_column('flags', 'default_value')
    op.drop_column('flags', 'type')
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_group_memberships_user_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_group_name'), table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    # ### end Alembic commands ###
