"""add indexes to feature_flags

Revision ID: 3504b2217a0f
Revises: 1985e30127ab
Create Date: 2026-07-30 18:59:50.853751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3504b2217a0f'
down_revision: Union[str, Sequence[str], None] = '1985e30127ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flags_environment_id'), 'flags', ['environment_id'], unique=False)
    op.create_index(op.f('ix_flags_key'), 'flags', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_key'), table_name='flags')
    op.drop_index(op.f('ix_flags_environment_id'), table_name='flags')
    # ### end Alembic commands ###
