"""create flags table

Revision ID: 93c0d7d19f95
Revises: 4aadab5112cd
Create Date: 2026-07-27 18:04:38.199379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c0d7d19f95'
down_revision: Union[str, Sequence[str], None] = '4aadab5112cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_environment_flag_key', 'flags', ['environment_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_environment_flag_key', 'flags', type_='unique')
    # ### end Alembic commands ###
