import { useEffect, useState } from "react";

function EnvironmentForm({ environment, isSubmitting, submitError, onClose, onSubmit }) {
  const [values, setValues] = useState({ name: environment?.name || "", description: environment?.description || "", is_active: environment?.is_active ?? true });
  const [errors, setErrors] = useState({});
  useEffect(() => { const onKey = (event) => event.key === "Escape" && !isSubmitting && onClose(); document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [isSubmitting, onClose]);
  const update = (field, value) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); };
  const submit = (event) => { event.preventDefault(); const next = {}; if (!values.name.trim()) next.name = "Enter an environment name."; else if (values.name.trim().length > 50) next.name = "Environment names must be 50 characters or fewer."; setErrors(next); if (!Object.keys(next).length) onSubmit({ name: values.name.trim(), description: values.description.trim() || null, is_active: values.is_active }); };
  return <div className="feature-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && !isSubmitting && onClose()}><section className="feature-modal environment-form-modal" role="dialog" aria-modal="true" aria-labelledby="environment-form-title"><div className="feature-modal-header"><div><p className="dashboard-eyebrow">Workspace configuration</p><h2 id="environment-form-title">{environment ? "Edit Environment" : "New Environment"}</h2><p>Keep release contexts clear and easy to operate.</p></div><button className="feature-modal-close" aria-label="Close environment form" disabled={isSubmitting} onClick={onClose} type="button">×</button></div><form className="feature-flag-form" noValidate onSubmit={submit}>{submitError && <div className="form-submit-error" role="alert">{submitError}</div>}<div className="form-field full-width"><label htmlFor="environment-name">Name</label><input id="environment-name" maxLength={50} value={values.name} onChange={(event) => update("name", event.target.value)} aria-invalid={Boolean(errors.name)} required />{errors.name && <span className="form-field-error">{errors.name}</span>}</div><div className="form-field full-width"><label htmlFor="environment-description">Description</label><textarea id="environment-description" rows="3" value={values.description} onChange={(event) => update("description", event.target.value)} placeholder="Describe this release context." /></div><label className="enabled-field"><input type="checkbox" checked={values.is_active} onChange={(event) => update("is_active", event.target.checked)} /> Active environment</label><div className="feature-form-actions"><button className="btn secondary" disabled={isSubmitting} onClick={onClose} type="button">Cancel</button><button className="btn primary" disabled={isSubmitting} type="submit">{isSubmitting ? "Saving…" : environment ? "Save Environment" : "Create Environment"}</button></div></form></section></div>;
}

export default EnvironmentForm;
