import { useEffect, useMemo, useState } from "react";
import { getAuditLogs, getEnvironments, getFlags } from "../services/api";

const actions = ["", "CREATE", "UPDATE", "ENABLE", "DISABLE", "DELETE", "TARGETING_RULE_CREATE", "TARGETING_RULE_UPDATE", "TARGETING_RULE_DELETE"];
function date(value) { if (!value) return "Not available"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "Not available" : parsed.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }); }
function label(action) { return action.startsWith("TARGETING_RULE_") ? `Rule ${action.replace("TARGETING_RULE_", "").toLowerCase()}` : action || "All actions"; }
function diffKeys(oldState, newState) { const keys = new Set([...Object.keys(oldState || {}), ...Object.keys(newState || {})]); return [...keys].filter((key) => JSON.stringify(oldState?.[key]) !== JSON.stringify(newState?.[key])); }

function AuditDetails({ record, onClose }) { useEffect(() => { const key = (event) => event.key === "Escape" && onClose(); document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [onClose]); const changed = diffKeys(record.old_state, record.new_state); return <div className="feature-modal-backdrop" role="presentation"><section className="feature-modal audit-details-modal" role="dialog" aria-modal="true" aria-labelledby="audit-details-title"><div className="feature-modal-header"><div><p className="dashboard-eyebrow">Audit detail</p><h2 id="audit-details-title">{label(record.action)}</h2><p>{record.actor} · {date(record.created_at)}</p></div><button className="feature-modal-close" onClick={onClose} type="button" aria-label="Close audit details">×</button></div><div className="audit-detail-summary">{changed.length ? changed.map((key) => <div key={key}><strong>{key}</strong><span>{record.old_state?.[key] === undefined ? "Added" : JSON.stringify(record.old_state[key])} → {record.new_state?.[key] === undefined ? "Removed" : JSON.stringify(record.new_state[key])}</span></div>) : <p>No field-level changes recorded.</p>}</div><div className="audit-json-grid"><div><h3>Previous state</h3><pre>{JSON.stringify(record.old_state || {}, null, 2)}</pre></div><div><h3>New state</h3><pre>{JSON.stringify(record.new_state || {}, null, 2)}</pre></div></div></section></div>; }

function AuditLogsPage() { const [records, setRecords] = useState([]); const [environments, setEnvironments] = useState([]); const [flags, setFlags] = useState([]); const [action, setAction] = useState(""); const [environment, setEnvironment] = useState(""); const [actor, setActor] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detail, setDetail] = useState(null);
  const load = async () => { setLoading(true); setError(""); try { const [auditResult, environmentResult, flagResult] = await Promise.all([getAuditLogs(), getEnvironments(), getFlags()]); setRecords(Array.isArray(auditResult) ? auditResult : []); setEnvironments(Array.isArray(environmentResult) ? environmentResult : []); setFlags(Array.isArray(flagResult) ? flagResult : []); } catch (requestError) { setError(requestError.message || "Unable to load audit logs."); } finally { setLoading(false); } }; useEffect(() => { const initialLoad = async () => { await load(); }; initialLoad(); }, []);
  const filtered = useMemo(() => records.filter((record) => (!action || record.action === action) && (!environment || String(record.environment_id) === environment) && (!actor || record.actor === actor) && (!search || `${record.actor} ${record.action} ${record.flag_id || ""}`.toLowerCase().includes(search.toLowerCase()))), [records, action, environment, actor, search]); const actors = [...new Set(records.map((record) => record.actor))]; const environmentName = (id) => environments.find((item) => item.id === id)?.name || `Environment #${id}`; const flagName = (id) => { const flag = flags.find((item) => item.id === id); return flag ? `${flag.name} (${flag.key})` : id ? `Flag #${id}` : "Environment activity"; };
  return <section className="audit-page"><div className="feature-page-header"><div><p className="dashboard-eyebrow">Workspace activity</p><h2>Audit Logs</h2><p>Review the recorded changes that shape your release configuration.</p></div></div><div className="audit-filters"><div><label htmlFor="audit-search">Search</label><input id="audit-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Actor, action, or flag ID" /></div><div><label htmlFor="audit-action">Action</label><select id="audit-action" value={action} onChange={(event) => setAction(event.target.value)}>{actions.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div><div><label htmlFor="audit-environment">Environment</label><select id="audit-environment" value={environment} onChange={(event) => setEnvironment(event.target.value)}><option value="">All environments</option>{environments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><label htmlFor="audit-actor">Actor</label><select id="audit-actor" value={actor} onChange={(event) => setActor(event.target.value)}><option value="">All actors</option>{actors.map((item) => <option key={item} value={item}>{item}</option>)}</select></div></div>{loading ? <div className="feature-page-state" role="status"><h2>Loading audit history</h2><p>Fetching recorded workspace activity.</p></div> : error ? <div className="feature-page-state feature-page-error" role="alert"><h2>Audit logs could not be loaded</h2><p>{error}</p><button className="btn secondary" onClick={load} type="button">Retry</button></div> : !records.length ? <div className="feature-empty-state"><h3>No audit activity yet</h3><p>Recorded flag and targeting-rule changes will appear here.</p></div> : !filtered.length ? <div className="feature-empty-state"><h3>No matching activity</h3><p>Try adjusting your filters.</p></div> : <div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Action</th><th>Actor</th><th>Environment</th><th>Flag</th><th>Timestamp</th><th>Details</th></tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td><span className={`audit-action audit-${record.action.toLowerCase()}`}>{label(record.action)}</span></td><td>{record.actor}</td><td>{environmentName(record.environment_id)}</td><td>{flagName(record.flag_id)}</td><td>{date(record.created_at)}</td><td>{(record.old_state || record.new_state) ? <button className="text-action" onClick={() => setDetail(record)} type="button">View changes</button> : "—"}</td></tr>)}</tbody></table></div>}{detail && <AuditDetails record={detail} onClose={() => setDetail(null)} />}</section>; }
export default AuditLogsPage;
